<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Be.Windows.Forms</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="BuiltInContextMenu.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="HexBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <EmbeddedResource Include="HexBox.bmp" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyTitle>Be.Windows.Forms.HexBox</AssemblyTitle>
    <Description>hex edit control %28C# DOTNET%29</Description>
    <Company>Be</Company>
    <Product>Be.Windows.Forms.HexBox</Product>
  </PropertyGroup>

</Project>