<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ACE.Adapter">
      <HintPath>lib\ACE.Adapter.dll</HintPath>
    </Reference>
    <Reference Include="ACE.Common">
      <HintPath>lib\ACE.Common.dll</HintPath>
    </Reference>
    <Reference Include="ACE.Database">
      <HintPath>lib\ACE.Database.dll</HintPath>
    </Reference>
    <Reference Include="ACE.Entity">
      <HintPath>lib\ACE.Entity.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="BufferedTreeView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="CustomListView.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Tools\map.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Be.Windows.Forms.HexBox\Be.Windows.Forms.HexBox.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Lists\CharacterList.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>

</Project>